{ config, pkgs, lib, ... }:

{
  # Darwin-level Homebrew configuration
  homebrew = {
    enable = true;
    onActivation.cleanup = "uninstall";
    enableZshIntegration = true;
    global.autoUpdate = true;

    brews = [
      "kubernetes-cli"
      "iproute2mac"
      "bat"
#      "helm"
      "docker"
      "pyenv"
      "stern"
      "vim"
      "awscli"
      "azure-cli"
      "go"
      "powerlevel10k"
      "tmux"
      "docker-compose"
      "colima"
      "lima"
      "podman"
      "tree"
      "htop"
      "pstree"
      "openssl@3"
      "rsync"
      "ssh-copy-id"
      "screen"
      "zsh-completions"
      "zsh-autosuggestions"
      "zsh-syntax-highlighting"
      "coreutils"
      "moreutils"
      "findutils"
      "binutils"
      "nmap"
      "socat"
      "dnstracer"
      "dnsx"
      "eksctl"
      "hcloud"
      "oci-cli"
      "kind"
      "minikube"
      "kubeshark"
      "k8sgpt"
      "k9s"
      "ansible"
      "ansible-lint"
      "opentofu"
      "p7zip"
      "jq"
      "yq"
      "fzf"
      "jo"
      "jless"
      "watch"
      "kubecolor"
    ];
    casks = [
      "windows-app"
      "zoom"
      "copyclip"
      "the-unarchiver"
      "mstystudio"
      "pearcleaner"
      "font-meslo-for-powerlevel10k"
      "maccy"
      "rancher"
      "caffeine"
      "grammarly-desktop"
      "claude"
      "rapidapi"
      "tailscale-app"
      "1password"
      "gcloud-cli"
      "slack"
      "visual-studio-code"
      "iterm2"
      "google-chrome"
      "obsidian"
      "bitwarden"
      "firefox"
      "vlc"
      "raycast"
      "dbeaver-community"
      ];
  };
}