{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
      awscli2
      azure-cli
      go
      google-cloud-sdk
      kubectl
      krew
      slack
      teleport
      tmux
      vim
      vscode
      iterm2
      obsidian
      bitwarden-desktop
      google-chrome
      maccy
      vlc-bin
      docker-compose
      colima
      lima
      podman
      handbrake
      google-cloud-sdk
      tree
      htop
      pstree
      openssl
      rsync
      ssh-copy-id
      screen
      zsh-completions
      zsh-autosuggestions
      zsh-syntax-highlighting
      nix-zsh-completions
      coreutils
      moreutils
      findutils
      binutils
      nmap
      socat
      dnstracer
      dnsx
      eksctl
      hcloud
      oci-cli
      kind
      minikube
      kubeshark
      k8sgpt
      k9s
      ansible
      ansible-lint
      opentofu
      imagemagick
      ffmpeg
      youtube-dl
      p7zip
      jq
      jo
      jless
      yq
      fzf
  ];
}
